global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Logging;
global using WebAPI.Models;
global using WebAPI.Logging;
global using System.Net;
global using Microsoft.AspNetCore.Diagnostics;
global using System.Diagnostics;
global using Newtonsoft.Json;
global using WebAPI.AppMIddleware;
